name:                raskell
version:             0.0.0.1
github:              "charlesfrye/raskell"
license:             BSD-3-Clause
author:              "Charles Frye"
maintainer:          "cfrye59@gmail.com"
copyright:           "Copyright (c) 2023 Charles Frye"

extra-source-files:
- README.md
- CHANGELOG.md

synopsis:            RASP-L in Haskell
category:            nlp

description:         Implements the RASP-L language from "What Algorithms Can Transformers Learn" by Zhou et al. For more information, see the README at <https://github.com/charlesfrye/raskell#readme>.

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:

  raskell-sort:
    main:                Sort
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - raskell

  raskell-count:
    main:                Count
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - raskell

tests:
  raskell-lib-test:
    main:                testLib.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - raskell
    - QuickCheck
  raskell-core-test:
    main:                testCore.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - raskell
    - QuickCheck

benchmarks:
  raskell-bench:
    main:                Bench.hs
    source-dirs:         bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - raskell
    - criterion
